import { isType } from '../../is/lib/is-type.func';
import { GuardType } from '../type/guard-type.type';
import { Types } from '../../type/types.type';
/**
 * Guard the `value` to be a generic `Type` type from one of the `Types` type.
 * Use `isType()` function for check ONLY.
 * @param value A generic `Type` value to guard.
 * @param type Constructor generic `Type`, `'function'`, `'object'` or one of the `Primitives` `'boolean'`, `'bigint'`, `'number'`, `'string'`, `'symbol'`, `'undefined'` to check `value`.
 * @example https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAwg9gOwM7AE4FcDGw6oDwAq4EAfFALxQIQDuUAFAHTMCGqA5kgFxQsIgBtALoBKCmSKQA3AChQkKAAVUASwC2K4CoBuEJBSgByAEYr2KhMENQAPkeNw4AGwh9rdwwnRrjEVO6MkEB9nAMMUVQR2MPQEABMIADMLCDjDWXloADFYzAMmZjA2FjUePhAxcjJyjOIoST08AHljACsySnhkNCwcfBb22yNE3K1EMLg2iGwA5XVNHT1ahQBJJAaDQmISem0WJ3QIMv4AGihMngakLcgSSrI9g+gVfQbZGUxEFCgXgCEzFaWfKPQ7HCo8EHPfSmcxAqrnYhwRJQSEUciUExmCxWWSfbo-JC-RwuPjA-ag3j8EQQ8lQqAOZyuBDiFG0n7dPiYCBIqBExmkmx2ei7Nnoyg9aCC1lPNGURL7JAQMQAMmVCMgPNRYvsxKZhhEuK+wAJMCcLCQ+kozTaO0mrWmwDBZwusCNGGwuGt7WpUDtDoJUAGLL92HZKE53ORmUN+JeADlvL5UGSnmCfaiXlRE34WZlNaL0UYvD4-NYAPwErIWTQQEVPMQ0mUWcMILk8hMl1Ax74vADKaAs7BTFPK6bZmYig9ziORWsL4QHUXSHyNBIAqvEkik4sOjpTwdLDgHYglktQd-C55QT1vz1BVerI4foNrDDez6ll3ie0gBv6rUGlDlDskJOlAADWEAgGWPCTlEY5NvogFkHms4FhiIZWPeaoZhyrZPn+oYVn2i7sPQkEVFAFYUeyz5QDwEr0VA8pOIq3bGi8OStmMzKUHWI5Uo2R6ZlxeTwqhdGviM3EqOM2F0c2wARjyok8exBK9sEDhOLuaZCXSQQhDp4kzpJ86Gdpy4rrG6zEDwawbFaDQgbSYEulcNykAhwmvHU8IAN4yFAPzIvQJGRGRmQiGIgXBcFSA0JomAABYMFFUCxXFwWYOa0CYrCVg8KgEDAOgqDMn8AKWPxSqyFl2W5Tq-IIIYRUlWVFWErqfA1QaQX1TlirDKMsktW1pXlZWI2IL1dUDY1njZv440dQSHZJrN-VZYNeWYa1UDFRNnWEcAnkufWc3bQtcHRCtk3hYOm31VAO2BFpoR3Z1mlGU981DW+m4fmkn3roD26-cFAC+-XQ8Fh2rZkVEmmaFpnTVzrEA2zEKhAsiQ+837Guw6BsHEjlQGjoH1MQGOQJcxDXM53l0o5ZAvA0lO0rTtUfCj+hdBE6BoHAprmvo-lQAAHgYACMUhQNDhOwAAMgAgr2vYAPoAGqq8ra4AKIGNQdACz0wuixa9B9UrvxNE0ysG6rcY63rhsGCxbHWd8vwrAA4iscYEK7+tG5QACcAAMkcAOwy+H4cAEwAKwACwx6nkcJzLCDqXGa4ALK-AbABKIfu5QMuJzH6m9gQJeB375dh0YBcgFmnYEl+XyMowThwGRAAGZsYBbfOD2cxOkxzI9C6gIt8zsMBqxrzdnLPY9i9F8sAPQ7+cGAQN7vf90PdsO07Lu66HE9QFPqBk8QeAMiSCA7OfjvO2vTWv-qBpQHvA+hxj4uD7gPegg9fYByDs3W+99H6QDwDdd+-tA7B2vobM4+VsR-13vvCUICIBgKHvnIupdNYEAABIlwNgbOBJMH4c2LEmHYpDi5lwwQbLBzDSzbwAfgw+hDiEQLYeQrITQ1wl3odPJ+yD6B1wbnGJunCsE3VwfwoBR8gA
 */
export const guardType: GuardType = <Type>(value: Type, type: Types<Type>): value is Type => isType<Type>(value, type);
